### ISSUE TITLE
Code is failing to obtain query results

### ISSUE THREAD

**Issue by NicolaSpreafico** [syslogic/google-apps-script#1]
Hi,
I'm using Datastore Lib and I have a query which ends with this result:
```
{
  "batch": {
    "entityResultType": "FULL",
    "endCursor": "CgA=",
    "moreResults": "NO_MORE_RESULTS",
    "snapshotVersion": "1579162924467171"
  },
  "query": {
    "kind": [
      {
        "name": "XXXX"
      }
    ],
    "filter": {
      "propertyFilter": {
        "property": {
          "name": "__key__"
        },
        "op": "HAS_ANCESTOR",
        "value": {
          "keyValue": {
            "partitionId": {},
            "path": [
              {
                "kind": "XXXX",
                "name": "yyyyyy"
              }
            ]
          }
        }
      }
    },
    "order": [
      {
        "property": {
          "name": "timestamp"
        },
        "direction": "DESCENDING"
      }
    ],
    "limit": 5
  }
}
```

And following code is throwing an error (line 240 of library)
```
        /* result.batch */
        if(typeof(result.batch) !== "undefined") {
          
          /* log the entityResults */
          for(i=0; i < result.batch["entityResults"].length; i++) {
            this.log(JSON.stringify(result.batch['entityResults'][i]));
          }
```

Key `result.batch` is there, so the first if is entering, but `result.batch["entityResults"]` is giving undefined, sto undefined.lenght is failing
I simply edited the linne like this
```
if(typeof(result.batch) !== "undefined" && typeof(result.batch.entityResults) !== "undefined") {
```

(also I suggest to move from `Logger.log` to `console.log` in order to use newer StackDriver Logging)

**Comment by syslogic** [comment]
This is not a library, but a script (which served as proof of concept once). You might construct a wrongful query (it seems as if nothing would be returned, as `moreResults: 'NO_MORE_RESULTS', endCursor: 'CgA='` suggests) and without the query/data which produces the issue, it is difficult to reproduce that. Just see [`QueryResultBatch`](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/runQuery#QueryResultBatch); this looks whole different than what you got there. Also, new Datastores might be Firestore in Datastore mode. Since it is [MIT ](https://github.com/syslogic/google-apps-script/blob/master/LICENSE) licensed, you can modify it however you like. Adding more dependencies doesn't necessarily make it any better, because not everybody uses StackDriver... and examples are meant to be minimal. Honestly, unless I'd add a `FUNDING.yml` and would get paid to fix the case of "no results", this probably won't happen.
